"""
Cross-language parity test.

Loads a fixture generated by scripts/generate-parity-fixture.ts (which runs
the REAL lib/ml/features.ts code, not a re-implementation) and asserts that
ml/preprocessing/features.py produces the same 89 numbers for the same input
landmarks. This is the test that guarantees a model trained in Python will
give correct predictions when fed browser-extracted features.

Regenerate the fixture after any change to the feature pipeline:
    npx tsx scripts/generate-parity-fixture.ts
"""
import json
import math
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from preprocessing.features import Point2D, extract_features  # noqa: E402

FIXTURE_PATH = os.path.join(os.path.dirname(__file__), "fixtures", "parity_fixture.json")
TOLERANCE = 1e-9


def load_fixture():
    with open(FIXTURE_PATH) as f:
        return json.load(f)


def test_fixture_exists():
    assert os.path.exists(FIXTURE_PATH), (
        "Fixture missing. Run: npx tsx scripts/generate-parity-fixture.ts"
    )


def test_python_matches_typescript_feature_vector():
    fixture = load_fixture()
    landmarks = [Point2D(p["x"], p["y"]) for p in fixture["landmarks"]]
    expected = fixture["features"]

    actual = extract_features(landmarks)

    assert len(actual) == len(expected) == 89
    for i, (a, e) in enumerate(zip(actual, expected)):
        assert math.isclose(a, e, abs_tol=TOLERANCE), (
            f"Feature {i} mismatch: python={a} typescript={e}"
        )


def test_feature_count_is_89():
    landmarks = [Point2D(0.1 * i, 0.2 * i) for i in range(21)]
    assert len(extract_features(landmarks)) == 89


def test_normalization_is_translation_invariant():
    """Shifting every landmark by the same offset must not change features
    (wrist-relative normalization should cancel out any pure translation)."""
    from preprocessing.features import normalize_landmarks

    base = [Point2D(0.1 + 0.03 * i, 0.5 - 0.02 * i) for i in range(21)]
    shifted = [Point2D(p.x + 0.37, p.y - 0.21) for p in base]

    norm_base = normalize_landmarks(base)
    norm_shifted = normalize_landmarks(shifted)

    for a, b in zip(norm_base, norm_shifted):
        assert math.isclose(a.x, b.x, abs_tol=1e-9)
        assert math.isclose(a.y, b.y, abs_tol=1e-9)
